
[x264.default]
preset = "ultrafast"
tune = "zerolatency"
profile = "main"
vbv_max_bitrate = 0
vbv_buffer_size = 0
fps_num = 24
fps_den = 1


[x264.lan]
[x264.wan]
[x264.broadband_high]
[x264.satellite]

[x264.broadband_low]
preset = "veryfast"
tune = "zerolatency"
vbv_max_bitrate = 1800
vbv_buffer_size = 40

[x264.modem]
preset = "fast"
tune = "zerolatency"
vbv_max_bitrate = 500
vbv_buffer_size = 40
